---

## Filtering section

# List of FieldIDs to extract, null to extract all
# See Data_Dictionary_Showcase.tsv for a concise list
FieldIDs:
# Ex: Sex
  - 31
# Instance aka timepoint, 1-4, null for all
InstanceIDs:
  - null
# Specific subjects to extract, null for all
SubjectIDs:
  - null
# Alternatively, one or more filenames which a flat lists of SubjectIDs
SubjectIDFiles:
  - null
# For fields with array components, null for all
ArrayIDs:
  - null
# Use pre-defined Categories of FieldIDs, added to list above, null for none
Categories:
  - null

## Output control section

# Replicate non-instanced data (aka Sex, other single-point measurements)
# across all instances
replicate_non_instanced: true

# Use data dictionary to recode FieldIDs as <Name>_<FieldID>
recode_field_names: true

# Use data dictionary and coding file to replace FieldValues with decoded entries
recode_data_values: true

# Some FieldValues were saved as empty strings instead of NA, drop these
drop_empty_strings: true

# Strings to drop as null
drop_null_strings:
  - "Do not know"
  - "Prefer not to answer"
  - "Time uncertain/unknown"
  - "Test not completed"
  - "Location could not be mapped"
  - "Abandoned"
  - "Next button not pressed"
  - "Trail not completed"
  - "Do not remember"
  - "Preferred not to answer"

# Numeric vaues to map to null
drop_null_numerics:
  - 99999
  - -9999999
  - -999999.000
  - -99999.000

## Wide output control

# Produce a wide aka pivoted DataFrame in addition to the filtered narrow frame
wide: true

# Use data dictionary to assign proper datatypes to columns in wide output
# Only applies to binary arrow format
recode_wide_column_valuetypes: true

# Attempt to split compound type FieldValues into a list in wide output
convert_compound_to_list: false

# When recode_wide_column_valuetype=true some values from recode_data_values=true
# some values will break setting column datatypes
# Substitute strings to values set below
convert_less_than_value_integer: null
convert_less_than_value_continuous: null
